version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://test:test@postgres:5431/test
    command: bash -c "flask db migrate && flask db upgrade && flask run -h 0.0.0.0"
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: "postgres"
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    command: -p 5431
